### ISSUE TITLE
Regarding using session

### ISSUE THREAD

**Issue by huchenhai** [OfficeDev/outlook-dev-docs#253]
Hi I'm writing an application uses Spring boot as Restful API, the session might not available at the backend. Is there another way to store token instead of using session? Eg database?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b06a747-de4f-325a-c543-13c6bdd60da6
* Version Independent ID: 8d4f3c2a-2661-5b9c-7a0f-ddc1145f594e
* Content: [How to use Outlook REST APIs in a Java Spring MVC Web app](https://docs.microsoft.com/en-us/outlook/rest/java-tutorial)
* Content Source: [docs/rest/java-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/java-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Yes, you can store the token in just about any way you want. The key thing is to make sure it's a secure storage.

**Comment by huchenhai** [comment]
Hi, could you please explain what the data table looks like? Should have separate table to store state, nonce and token ?

**Comment by jasonjoh** [comment]
There's no real required data format here. What I would do is store only the refresh token (**not the access token** ) and the user's unique ID from their ID token in long-term storage. That way you can always look up the user's refresh token and use that to obtain a fresh access token.

Access tokens are only valid for an hour so I wouldn't bother storing them in a database (and since they're usable to get at customer data, it's better to avoid storing them anyway!). I'd look at maybe keeping those in some sort of dynamic cache on your backend, again mapped to the user's ID.

State and nonce are throw-away values that aren't valid past their single use, so don't store those long-term either.

**Comment by huchenhai** [comment]
thank you so much

**Comment by hshoushari** [comment]
hello, i am trying to fetch user emails from outlook to my spring project, 
in my case the user is already authenticated and authorized by active directory, and the outlook account is Microsoft exchange account,  and i need to fetch the user email without passing credentials because the user is already authenticated.

Kindly advice.

**Comment by jasonjoh** [comment]
Nothing specific. I would secure it like any other sensitive customer data. The Azure folks might have more specific guidance if you asked on Stack Overflow with the `azure-authentication` tag.

**Comment by huchenhai** [comment]
Hi Shivasurya, what I did was creating a token table associated with user
table and stuff like refresh token and expiry time are all stored there.
Saving a refresh token has nothing special, just do as a normal string. And
whenever check a token, compare it's expiry time.

**Comment by shivasurya** [comment]
Thank you @huchenhai , it would be better to encrypt and store.
