### ISSUE TITLE
Webpack?

### ISSUE THREAD

**Issue by stevechilds** [OfficeDev/outlook-dev-docs#328]
This is fine, but it doesn't mention webpack at all, which is included in the template generated by "yo office". The new files (dialog / helpers etc.. don't appear to be picked up by webpack and so the sample does not work if you follow the instructions...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b98fcab-f608-d0dd-08ab-633d4772f699
* Version Independent ID: ad0a00c9-e5c2-fdfc-732e-f14869088f4a
* Content: [Advanced Outlook Add-in tutorial](https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial)
* Content Source: [docs/add-ins/addin-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/addin-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by lindalu-MSFT** [comment]
@nokafor Hi Sylvia, here's another Yo Office setup issue. Can you assist @ElizabethSamuel-MSFT figure out what we need to do to fix the steps in this tutorial so that they work for the customer?

**Comment by ElizabethSamuel-MSFT** [comment]
Microsoft internal use: https://office.visualstudio.com/OC/_workitems/edit/2556013

**Comment by ElizabethSamuel-MSFT** [comment]
Closing this. @stevechilds: please reactivate if you're still facing an issue. Thanks.

**Comment by djpereira** [comment]
The sample does work but it is misleading, as it is not using webpack properly.

For example, in webpack.config.js you do have the function-file.html and funtion-file.js properly configured as an "entry".

However then in function-file.html, all script files are brought in via script tag instead of using imports:

```html
    <script type="text/javascript" src="../node_modules/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="../node_modules/showdown/dist/showdown.min.js"></script>
    <script type="text/javascript" src="../node_modules/urijs/src/URI.min.js"></script>
    <script type="text/javascript" src="../helpers/addin-config.js"></script>
    <script type="text/javascript" src="../helpers/gist-api.js"></script>
    <script type="text/javascript" src="function-file.js"></script>
```

And also function-file.js ends up included twice in the output, once via manual script and once via webpack.

I understand this is just a sample, but with the way is setup right now, is difficult to understand how to grow it into a more complete solution.

What do y'all think about modifying the sample in a way that uses webpack correctly, as is intended by the "yo office" generator?

**Comment by lindalu-MSFT** [comment]
@ElizabethSamuel-MSFT Do you want to reopen this issue or open a new one? It looks like there are a couple of things that should be addressed in this sample. Thanks, lindalu

**Comment by ElizabethSamuel-MSFT** [comment]
@djpereira: Thanks for sharing. We'll take a look.

**Comment by kbrandl** [comment]
Closing this issue now, as I it should have been resolved by recent updates to Yo Office and to the tutorial instructions. Please comment here if that's not the case and this issue needs to be re-opened. Thanks!
