### ISSUE TITLE
no index.js

### ISSUE THREAD

**Issue by TobyFish** [OfficeDev/outlook-dev-docs#340]
There is no index.js in the add-in route directory as specified above. There are many in the none_modules folders and there is an index.ts in the function-file folder. 
Please advise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15be7148-d1e8-b58b-b026-9f072efb638a
* Version Independent ID: 53a5d00c-d82b-6536-2e80-3e2a3452879a
* Content: [Build an Outlook Add-in](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code)
* Content Source: [docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
It appears the Office Add-in generator changed pretty significantly since that quick-start was written, so this walkthrough needs to be re-written. @lindalu-MSFT can you get a writer assigned?

@TobyFish when I ran the latest generator, I see a `./src/index.js` file. This is with yo 2.0.5 and generator-office 1.1.15.

![image](https://user-images.githubusercontent.com/8966342/44039722-a855ef2e-9ee7-11e8-9e18-22de24331a71.png)

![image](https://user-images.githubusercontent.com/8966342/44039759-bf2bc8c2-9ee7-11e8-8393-28d2bedcee2a.png)

**Comment by ElizabethSamuel-MSFT** [comment]
As @jasonjoh notes, index.js is now in a sub-folder. Apologies for the confusion. The update should go live soon but hopefully this info unblocks you.

**Comment by lindalu-MSFT** [comment]
@ElizabethSamuel-MSFT Thanks for fixing.

**Comment by TobyFish** [comment]
Thanks for the pointers. All I see in that folder is an index.ts, not an index.js, are the two used interchangeably?

**Comment by ElizabethSamuel-MSFT** [comment]
@TobyFish It seems like you may be doing a different quick start. Can you share more details about the steps you were followed? Thanks.

**Comment by TobyFish** [comment]
this one https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code

**Comment by ElizabethSamuel-MSFT** [comment]
@TobyFish I think I understand what happened. We provide steps for the script type "Javascript". I believe you ended up selected "Typescript" instead:
![image](https://user-images.githubusercontent.com/28541963/44157610-b8f5eb00-a067-11e8-93e5-faee0cf4d3dc.png)

Please try the Javascript option to follow along with the tutorial.

Thanks.
