### ISSUE TITLE
Exchange identity token validation using python

### ISSUE THREAD

**Issue by vinaysheelwagh** [OfficeDev/outlook-dev-docs#347]
We are working on validation of exchange identity token using python library [PyJWT](https://pyjwt.readthedocs.io/en/latest/). In the document("") it is mentioned that there are various libraries to validate Exchange user identity tokens.  Please let us know if [PyJWT](https://pyjwt.readthedocs.io/en/latest/) will work for Exchange user token validation. Is it something like that Exchange identity token validation can only be done in .NET or other language will also work.

**Comment by VaibhavTyson** [comment]
facing same issue on my Linux environment.

**Comment by ElizabethSamuel-MSFT** [comment]
@vinaysheelwagh: Were you referring to this document: https://docs.microsoft.com/en-us/outlook/add-ins/validate-an-identity-token#use-a-library-to-validate-the-token? If so, we can speak to the libraries mentioned there. Otherwise, you may want to ask the StackOverflow community for their input on this, tagged with the [office-js](https://stackoverflow.com/questions/tagged/office-js) and [outlook-web-addins](https://stackoverflow.com/questions/tagged/outlook-web-addins) tags? Thanks!
