### ISSUE TITLE
How to connect this with visual studio

### ISSUE THREAD

**Issue by salimguerid** [OfficeDev/outlook-dev-docs#460]
Interesting tutorial but how to connect it with a visual studio project? The first tutorial was using VS but this one is outside and therefore not really convenient to maintain. Is there a way to run this project using VS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b98fcab-f608-d0dd-08ab-633d4772f699
* Version Independent ID: ad0a00c9-e5c2-fdfc-732e-f14869088f4a
* Content: [Tutorial: Build a message compose Outlook add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial)
* Content Source: [docs/add-ins/addin-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/addin-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh

**Comment by kbrandl** [comment]
@salimguerid thanks for your interest in Outlook add-ins development. Since the file names and folder structure of the project that Yo Office (i.e., the Yeoman Generator for Office Add-ins) creates differs from the file names and folder structure of a Visual Studio project, a project that you create using Yo Office (as is done in this tutorial) cannot be run using Visual Studio. 

However, you could create a new Outlook add-in project using Visual Studio, and then *generally* follow the instructions in the tutorial to make the same code changes and additions in your Visual Studio project. If you do this, please note that the file names and file locations (folder names and paths) in the tutorial instructions in some cases may not correspond to file names and file locations within the Visual Studio project -- so in those cases you'd have to figure out which file in the Visual Studio project corresponds to the file that the tutorial instructions reference. For example, the name and location of the XML manifest file is different in the project that Yo Office creates, compared to the project that Visual Studio creates.
