### ISSUE TITLE
Warning: Office.js is loaded outside of Office client

### ISSUE THREAD

**Issue by shaikhshadab00** [OfficeDev/outlook-dev-docs#480]
I am following each step one by one to create outlook Add-in by using Node.js and yo generator-office. write a command to start the web server and load a URL of index.html 'https://localhost:3000'. page load properly but getting an warning message on console "Warning: Office.js is loaded outside of Office client"  and can't parse office item to fetch message. in .js file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15be7148-d1e8-b58b-b026-9f072efb638a
* Version Independent ID: 53a5d00c-d82b-6536-2e80-3e2a3452879a
* Content: [Build an Outlook add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code)
* Content Source: [docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by kbrandl** [comment]
@shaikhshadab00 sorry to hear that you've run into this problem. Are you seeing the "Warning: Office.js loaded outside of Office Client" message whenever you load `https://localhost:3000` in a web browser (as described in [step #2](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code#start-the-dev-server) in the **Start the dev server** section of this article)? If so, that's expected behavior in the browser (because your add-in won't function properly outside the context of Outlook). 

If you haven't already done so, please try to complete the instructions in the [Try it out](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code#try-it-out) section of the article, including (especially) [step 1 - Sideload the Outlook add-in for testing](https://docs.microsoft.com/en-us/outlook/add-ins/sideload-outlook-add-ins-for-testing). You shouldn't see the "Warning: Office.js loaded outside of Office Client" message when the add-in loads within Outlook. Please let me know if you're still having trouble after attempting to sideload and use the add-in in Outlook.

**Comment by shaikhshadab00** [comment]
@kbrandl Thank you for prompt reply. i am not getting any warning message when the add-in loads within Outlook. work perfectly fine now.
