### ISSUE TITLE
Outlook Professional Plus 2016 new add-in issue

### ISSUE THREAD

**Issue by mpasharpsl** [OfficeDev/outlook-dev-docs#656]
Hello,
I'm using Office Professional Plus 2016, on windows 10. Is there a way to add a new add-in via URL in Outlook?
I know this is possible in desktop app of the Outlook Office 365. But I need to do this in Office Professional Plus.

Thanks!
Malika

**Comment by mpasharpsl** [comment]
To add more info, I'm connected to Exchange 2010 server of our company network. Is that make any different how we access add-ins?

**Comment by ElizabethSamuel-MSFT** [comment]
@mpasharpsl Thanks for asking about this. Exchange 2010 doesn't support add-ins unfortunately. You need to be on Exchange 2013 or later for add-ins support. Note that Exchange server support can also be more limited than what the desktop, web, or mobile client may otherwise support.

[Supported clients](https://docs.microsoft.com/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#clients)

I'll go ahead and close this issue but if you have any further questions, let us know and we can reopen it.

Thanks.
