### ISSUE TITLE
Exchange server 2019?

### ISSUE THREAD

**Issue by sagarpilkhwal** [OfficeDev/outlook-dev-docs#700]
Will makeEwsRequestAsync work on Exchange server 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd670845-f60e-c6a0-090a-aa5f7246fa07
* Version Independent ID: 77bd64a6-8d77-1266-d812-798f35563b89
* Content: [Use Exchange Web Services (EWS) from an Outlook add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/web-services#feedback)
* Content Source: [docs/add-ins/web-services.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/web-services.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@sagarpikhwal Thanks for your question. [makeEwsRequestAsync](https://docs.microsoft.com/office/dev/add-ins/reference/objectmodel/requirement-set-1.5/Office.context.mailbox#makeewsrequestasyncdata-callback-usercontext) was introduced since the inception of Mailbox add-ins (requirement set 1.0) so [on-premises Exchange 2013 and later](https://docs.microsoft.com/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#clients) should support it.

Let us know if you find that is not the case so we can investigate.

Thanks.
