### ISSUE TITLE
UX styling across 365, ios and android

### ISSUE THREAD

**Issue by ftwcreative** [OfficeDev/outlook-dev-docs#719]
Just to be clear, If we were to use https://mobiscroll.com/ and used the native UI/UX style out of the box, this will be approved by your team to use across 365,ios and android? From what I have read, you recommend using fabric, but using a native ux design is better?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef2c9cc-3f5b-b2b1-dd84-08a910a74c64
* Version Independent ID: df0d841a-6e7b-bb95-99b8-dae7fc950f35
* Content: [Outlook add-in design - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/outlook-addin-design#feedback)
* Content Source: [docs/add-ins/outlook-addin-design.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/outlook-addin-design.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
Unfortunately, the Validation Team can't assist with Technical issues. However, looking at the documentation: 

https://docs.microsoft.com/en-us/outlook/add-ins/outlook-mobile-addins

Notably the following sections: 

What's different on mobile?
•	The small size and quick interactions make designing for mobile a challenge. To ensure quality experiences for our customers, we are setting strict validation criteria that must be met by an add-in declaring mobile support, in order to be approved in AppSource.
o	The add-in MUST adhere to the UI guidelines.
o	The scenario for the add-in MUST make sense on mobile.


Make it feel as native as possible

This does mean that your add-in will have to visually be different when it runs in Outlook on iOS versus Android. We recommend taking a look at Framework7 as one option to help you with styling.

**Comment by ElizabethSamuel-MSFT** [comment]
@ftwcreative Thanks for your query. Sorry we can't be more specific. Further to exextoc's response, you should also try to blend with the look-and-feel of Outlook and your own company/app branding.

I'll close this issue now but if you have any further questions on this, let us know and we can reopen this issue.

Thanks.
