### ISSUE TITLE
Not configured as multi-tenant application

### ISSUE THREAD

**Issue by nabgilby** [OfficeDev/outlook-dev-docs#741]
Is this tutorial not up to date? getting this error:

Message: AADSTS50194: Application '609b1820-f15d-4907-8305-af916d1437f4'(JavaScript Outlook Tutorial) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b3b79de-f858-e70c-caab-699eccf9772c
* Version Independent ID: 95a9cdad-2ad6-93b7-00c6-877633a9cead
* Content: [Using Outlook REST APIs in a JavaScript single-page app - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/javascript-tutorial#feedback)
* Content Source: [docs/rest/javascript-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/javascript-tutorial.md)
* Product: **outlook**
* Technology: **ms-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
The error indicates that the app registration was configured a bit differently than the tutorial lays out. Specifically:

> Set Supported account types to Accounts in any organizational directory and personal Microsoft accounts.

If you set it to "Accounts in my organization only", then the tutorial would need to be modified. You would need to replace `common` with your tenant ID in this line:

```
var authEndpoint = 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize?';
```

**Comment by nabgilby** [comment]
Thank you, still not quite working and really this should be a simple tutorial that just works.

So I've:
1. set the supported account types to Accounts in any organizational directory (Any Azure AD directory - Multitenant)

2. tried both below, as now where could I find an example and the documentation of {tenant} is not clear

  var authEndpoint = 'https://login.microsoftonline.com/99731b89-3b9a-42f8-addd-c54768248043/oauth2/v2.0/authorize?'; 

var authEndpoint = 'https://login.microsoftonline.com/{99731b89-3b9a-42f8-addd-c54768248043}/oauth2/v2.0/authorize?'

But I am not able to authenticate and now I get a flashing error in the url field, is there an example I can follow that works for these authentication parameters somewhere?

**Comment by jasonjoh** [comment]
I agree it should "just work", which is why I chose to use the mutlitenant registration so you can just use `common` in your authorize URL. I figured that would be less steps :). If you've changed your app registration to be multitenant then you should be good with the original value of `authEndpoint`. However to answer your question about #2, the first version you list there is the correct format. The GUID you should use is found on the **Overview** page of your app registration in the **Directory (tenant) ID** field.

In fairness this tutorial hasn't been updated in a while, so let me run through it real quick to see if anything needs updating. If you're looking for a more recent JS tutorial, we have two JS-based tutorials on the Graph site, though they use React and Angular frameworks (where this one is just plain JavaScript). Not sure if that works for you.

**Comment by jasonjoh** [comment]
Ok, I found what is likely the cause of a lot of the issues you're hitting. Azure changed the app registration process a bit from the time of the last update to this tutorial.

In step 5 under **Register the app**, the tutorial tells you to enable ID tokens under **Implicit grant**. You now also need to enable Access tokens there as well, and be sure to save the change before retrying your app.

![image](https://user-images.githubusercontent.com/8966342/67123564-abce1200-f1be-11e9-91fd-398ef8304323.png)

**Comment by jasonjoh** [comment]
One other thing you'll hit: The Graph SDK no longer has their JS file downloadable from GitHub. So ignore this bit:

> Let's start by downloading the Microsoft Graph JavaScript Client Library. We already added a reference to it in the HTML, so all we need to do is download it. Go to https://github.com/microsoftgraph/msgraph-sdk-javascript and download the source. Copy the ./lib/graph-js-sdk-web.js into the javascript-tutorial directory.

Instead, change this line in index.html:

```
<script src="graph-js-sdk-web.js"></script>
```

To this:

```
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@microsoft/microsoft-graph-client/lib/graph-js-sdk.js"></script>
```

**Comment by jasonjoh** [comment]
Full list of issues found:

- [Bug with http-server](https://github.com/http-party/http-server/issues/525). Should update to specify version 0.9.0 when installing
- Need to remove `buildAuthUrl` method in the initial outlook-demo.js (since the function doesn't exist yet)
- Need to enable access tokens under Implicit grant in app registration
- Typo (Subract)
- SDK file is no longer on GitHub, need to change to use the script tag from their README

**Comment by jasonjoh** [comment]
Tutorial has been retired per https://github.com/OfficeDev/outlook-dev-docs/pull/851.
