### ISSUE TITLE
"Summary or Text is required"

### ISSUE THREAD

**Issue by JasonGoemaatAtCorteva** [OfficeDev/outlook-dev-docs#742]
Not sure what that means...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2606e423-7aff-b44e-3c88-1a96d16ed1fc
* Version Independent ID: 29e8d7ba-d255-f533-7781-aa2aa14a040e
* Content: [Get started with actionable messages via connectors - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-connectors#feedback)
* Content Source: [docs/actionable-messages/send-via-connectors.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/send-via-connectors.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Did you get this as an error? I believe MessageCards do require either a value in the `summary` or the `text` field.

**Comment by jasonjoh** [comment]
I don't reproduce this with the JSON that's in the article, which has a `text` property. If I understand correctly, you're saying that when you modify the card in the designer, you remove that property (because it isn't clear that it's required)?

**Comment by krmeda** [comment]
I got to the link above following this route:
1. Click on "Get Started with Office 365 Connector Cards" link in the picture
![image](https://user-images.githubusercontent.com/1650033/67899533-dca43480-fb38-11e9-8177-b47f259a5d28.png)
2. Navigate to "Card Playground" link from this page. 
3. Card Playground creates ActionCards. 
4. Copy the JSON from playground and continue on to "Send a Message" section of the document. 
5. Error shows up (because Teams only supports MessageCards and the Card Playground only creates Action Cards. Message Card examples are grayed out.)

**Comment by jasonjoh** [comment]
Ok, so the example JSON on the page isn't part of the equation at all then?

You go to the playground (https://messagecardplayground.azurewebsites.net/) which defaults to Adaptive Cards, which aren't supported by Teams (or any connector). MessageCard samples are available in the dropdown:

![image](https://user-images.githubusercontent.com/8966342/67902603-ed0bdd80-fb3f-11e9-968f-454c2390d638.png)

It sounds like the topic needs a callout to specify that the AdaptiveCard format is not supported via connectors.

**Comment by cssandstuff** [comment]
Will the AdaptiveCard format ever be supported via connectors?

**Comment by jasonjoh** [comment]
@cssandstuff AFAIK there have been no announcements about bringing Adaptive to connectors.
