### ISSUE TITLE
Graph endpoint is returning a different user ID from the Outlook endpoint

### ISSUE THREAD

**Issue by sjlu** [OfficeDev/outlook-dev-docs#918]
The Graph endpoint is returning a different user ID from the Outlook endpoint. Is this expected behavior or is there a way to normalize the two IDs?

**GET https://outlook.office.com/api/v2.0/Me**
```
{
  '@odata.context': 'https://outlook.office.com/api/v2.0/$metadata#Me',
  '@odata.id': "https://outlook.office.com/api/v2.0/Users('0003bffd-0fe5-50a1-0000-000000000000@84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa')",
  Id: '0003bffd-0fe5-50a1-0000-000000000000@84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa',
  EmailAddress: 'tacticalazn@outlook.com',
  DisplayName: 'Steven Lu',
  Alias: 'puid-0003BFFD0FE550A1',
  MailboxGuid: '0003bffd-0fe5-50a1-0000-000000000000'
}
```

**GET https://graph.microsoft.com/v1.0/me**
```
{
  '@odata.context': 'https://graph.microsoft.com/v1.0/$metadata#users/$entity',
  displayName: 'Steven Lu',
  surname: 'Lu',
  givenName: 'Steven',
  id: 'fde926f844473904',
  userPrincipalName: 'tacticalazn@outlook.com',
  businessPhones: [],
  jobTitle: null,
  mail: null,
  mobilePhone: null,
  officeLocation: null,
  preferredLanguage: null
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78f042c4-37ce-4588-23df-98b73a783c70
* Version Independent ID: 3c3b3a02-a41a-d894-6aed-aed1fd20c36e
* Content: [Compare Microsoft Graph and Outlook endpoints - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/compare-graph#moving-from-outlook-endpoint-to-microsoft-graph)
* Content Source: [docs/rest/compare-graph.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/rest/compare-graph.md)
* Product: **outlook**
* Technology: **ms-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
The Outlook endpoint generates IDs as `<objectId>@<tenantId>`, where `objectId` is the id of the user in Azure AD. For Azure AD accounts (work or school, etc.) the Graph ID will be the `objectId` of the user, so it's easy to correlate. For personal accounts like the one you're showing, it's not so easily mapped.

The Outlook endpoint uses the same format for personal, where `84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa` is a generic tenant ID for personal accounts (since they're not part of a "tenant"). However, since they're not an Azure AD account, there's no `objectId` to use. You may have noticed that it uses the mailbox GUID instead. The Graph uses a simpler format for personal accounts - I'm not aware of how it's derived.

In Graph, you can do `GET https://graph.microsoft.com/v1.0/me/outlook` and you'll get the same `id` that you get from the Outlook endpoint.

**Comment by sjlu** [comment]
Thanks @jasonjoh - closing this out but def useful information for the docs!
